### ISSUE TITLE
Cannot require the module

### ISSUE THREAD

**Issue by diego92sigma6** [sgratzl/chartjs-chart-graph#15]
Hi, thanks for publishing this library!
When I require the module in my React App, I get a strange require error - see below

**To Reproduce**

Import the library using a normal require
```js
var test = require('chartjs-chart-graph')
console.log(test)
```

Another example with an actual portion of the code I'm using:
```typescript
import { makeStyles } from "@material-ui/core"
import React from "react"
import { useEffect, useState } from "react"
import { ApiService } from "../../../services/Api.service"
import { Project } from "../../../types/project"
import { Chart } from "chart.js"
import { ForceDirectedGraphController, EdgeLine } from 'chartjs-chart-graph';
debugger

const useStyles = makeStyles(theme => ({
    root: {

    },
    canvas: {
        maxWidth: '50%',
        marginLeft: 'auto',
        marginRight: 'auto'
    },
}))

```

**Expected behavior**
Object is imported

**Actual Behavior**
```
TypeError: Cannot read property 'forEach' of undefined
    at http://localhost/static/js/1.chunk.js:77423:92
    at Module../node_modules/chartjs-chart-graph/build/index.esm.js (http://localhost/static/js/1.chunk.js:77427:5)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Module../src/components/project/results/TaxaChart.tsx (c:\Users\dmarq\Documents\proteus\dayhoff\web\src\components\project\results\TaxaChart.tsx:7:1)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Module../src/components/project-list/ProjectCollapsibleRow.tsx (http://localhost/static/js/main.chunk.js:3953:84)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Module../src/components/project-list/ProjectsTable.tsx (http://localhost/static/js/main.chunk.js:4883:80)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Module../src/components/project-list/Projects.tsx (http://localhost/static/js/main.chunk.js:4615:72)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Module../src/App.tsx (http://localhost/static/js/main.chunk.js:228:91)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Module../src/index.tsx (http://localhost/static/js/main.chunk.js:6928:62)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at fn (http://localhost/static/js/bundle.js:151:20)
    at Object.1 (http://localhost/static/js/main.chunk.js:7332:18)
    at __webpack_require__ (http://localhost/static/js/bundle.js:785:30)
    at checkDeferredModules (http://localhost/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost/static/js/bundle.js:33:19)
    at http://localhost/static/js/main.chunk.js:1:59
```

**Context**

- Version: ^3.0.0-beta.9
- Chart.js version: 3.0.0-beta.13
- Browser: Chrome

**Additional context**
What I have tried
- Manually importing the library by downloading the source code
- Cloning my own project on another folder
- Use import syntax instead

Please let me know if you need details on anything else

**Comment by diego92sigma6** [comment]
Thanks for the reply. I'll try using beta.9 on both libraries and will let you know how it goes.

**Comment by diego92sigma6** [comment]
@sgratzl, it indeed worked when both libraries got locked at 3.0.0-beta.9. I submitted a small PR to specify this on the readme
